// Code generated by MockGen. DO NOT EDIT.
// Source: storyline.go
//
// Generated by this command:
//
//	mockgen -source=storyline.go -destination=../mocks/repository/storyline_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"
	time "time"

	repository "github.com/Ra1ze505/goNewsBot/src/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockStorylineRepositoryInterface is a mock of StorylineRepositoryInterface interface.
type MockStorylineRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorylineRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockStorylineRepositoryInterfaceMockRecorder is the mock recorder for MockStorylineRepositoryInterface.
type MockStorylineRepositoryInterfaceMockRecorder struct {
	mock *MockStorylineRepositoryInterface
}

// NewMockStorylineRepositoryInterface creates a new mock instance.
func NewMockStorylineRepositoryInterface(ctrl *gomock.Controller) *MockStorylineRepositoryInterface {
	mock := &MockStorylineRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockStorylineRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorylineRepositoryInterface) EXPECT() *MockStorylineRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateStoryline mocks base method.
func (m *MockStorylineRepositoryInterface) CreateStoryline(s *repository.Storyline) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoryline", s)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoryline indicates an expected call of CreateStoryline.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) CreateStoryline(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoryline", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).CreateStoryline), s)
}

// DeleteObservationsForDate mocks base method.
func (m *MockStorylineRepositoryInterface) DeleteObservationsForDate(channelID int64, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObservationsForDate", channelID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObservationsForDate indicates an expected call of DeleteObservationsForDate.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) DeleteObservationsForDate(channelID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObservationsForDate", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).DeleteObservationsForDate), channelID, date)
}

// GetActive mocks base method.
func (m *MockStorylineRepositoryInterface) GetActive(channelID int64) ([]repository.Storyline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", channelID)
	ret0, _ := ret[0].([]repository.Storyline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) GetActive(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).GetActive), channelID)
}

// GetStats mocks base method.
func (m *MockStorylineRepositoryInterface) GetStats(storylineID int64, before time.Time, windowDays int) (repository.StorylineStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", storylineID, before, windowDays)
	ret0, _ := ret[0].(repository.StorylineStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) GetStats(storylineID, before, windowDays any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).GetStats), storylineID, before, windowDays)
}

// MarkClosed mocks base method.
func (m *MockStorylineRepositoryInterface) MarkClosed(channelID int64, lastSeenBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkClosed", channelID, lastSeenBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkClosed indicates an expected call of MarkClosed.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) MarkClosed(channelID, lastSeenBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkClosed", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).MarkClosed), channelID, lastSeenBefore)
}

// MarkDormant mocks base method.
func (m *MockStorylineRepositoryInterface) MarkDormant(channelID int64, lastSeenBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDormant", channelID, lastSeenBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDormant indicates an expected call of MarkDormant.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) MarkDormant(channelID, lastSeenBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDormant", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).MarkDormant), channelID, lastSeenBefore)
}

// ResetChannel mocks base method.
func (m *MockStorylineRepositoryInterface) ResetChannel(channelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetChannel", channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetChannel indicates an expected call of ResetChannel.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) ResetChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetChannel", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).ResetChannel), channelID)
}

// SaveObservation mocks base method.
func (m *MockStorylineRepositoryInterface) SaveObservation(o *repository.Observation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveObservation", o)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveObservation indicates an expected call of SaveObservation.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) SaveObservation(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveObservation", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).SaveObservation), o)
}

// SearchNearest mocks base method.
func (m *MockStorylineRepositoryInterface) SearchNearest(channelID int64, query []float32, k int) ([]repository.ScoredStoryline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNearest", channelID, query, k)
	ret0, _ := ret[0].([]repository.ScoredStoryline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNearest indicates an expected call of SearchNearest.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) SearchNearest(channelID, query, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNearest", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).SearchNearest), channelID, query, k)
}

// UpdateStoryline mocks base method.
func (m *MockStorylineRepositoryInterface) UpdateStoryline(s *repository.Storyline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoryline", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStoryline indicates an expected call of UpdateStoryline.
func (mr *MockStorylineRepositoryInterfaceMockRecorder) UpdateStoryline(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoryline", reflect.TypeOf((*MockStorylineRepositoryInterface)(nil).UpdateStoryline), s)
}
