version: '3.8'

services:
  app:
    image: ra1zee/gonewsbot:latest
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./session:/app/session
      - ./authorized_key.json:/app/authorized_key.json
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --label-enable
      - --cleanup
      - --interval
      - "60"
